environment:
  matrix:
  - JULIAVERSION: "julialang/bin/winnt/x86/0.4/julia-0.4-latest-win32.exe"
  - JULIAVERSION: "julialang/bin/winnt/x64/0.4/julia-0.4-latest-win64.exe"

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

install:
# Download most recent Julia Windows binary
  - ps: (new-object net.webclient).DownloadFile(
        $("http://s3.amazonaws.com/"+$env:JULIAVERSION),
        "C:\projects\julia-binary.exe")
# Run installer silently, output to C:\projects\julia
  - C:\projects\julia-binary.exe /S /D=C:\projects\julia
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaOptimizers/NLPModels.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"NLPModels\", \"develop\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaOptimizers/OptimizationProblems.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.add(\"DistributedArrays\"); Pkg.build(\"DistributedArrays\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/optimizers/Krylov.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"Krylov\", \"develop\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/dpo/LinearOperators.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"LinearOperators\", \"develop\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaOptimizers/AmplNLReader.jl.git\")"
  - C:\projects\julia\bin\julia -e "Pkg.checkout(\"AmplNLReader\", \"nlpmodel\")"
  - C:\projects\julia\bin\julia -e "Pkg.build(\"AmplNLReader\")"
  - C:\projects\julia\bin\julia -e "Pkg.clone(\"https://github.com/JuliaOptimizers/Profiles.jl.git\")"

build_script:
# Need to convert from shallow to complete for Pkg.clone to work
  - IF EXIST .git\shallow (git fetch --unshallow)
  - C:\projects\julia\bin\julia -e "versioninfo();
      Pkg.clone(pwd(), \"Optimize\"); Pkg.build(\"Optimize\")"

test_script:
  - C:\projects\julia\bin\julia --check-bounds=yes -e "Pkg.test(\"Optimize\")"
